language: python
python:
  - "2.7"

addons:
  apt:
    sources:
    - r-packages-precise

services:
 - postgresql
 - memcached
 - rabbitmq

virtualenv:
  system_site_packages: true

before_install:
 - psql -c 'create database amcat;' -U postgres
 - export DJANGO_DB_USER=postgres
 - export DJANGO_LOG_LEVEL=WARNING
 - export DJANGO_SETTINGS_MODULE=settings
 - export TRAVIS=true
 - export AMCAT_ES_LEGACY_HASH=0
 - export PYTHONPATH=
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 2 # Give framebuffer some time to start

install:
 - sudo apt-get update
 - cat apt_requirements.txt | tr '\n' ' ' | xargs sudo apt-get install -y
 - sudo service rabbitmq-server start
  # Latest PSPP (present in 15.04, 15.10, 16.04 archives)
 - sudo apt-get install debhelper dh-apparmor gir1.2-atk-1.0 gir1.2-gtk-2.0 gir1.2-pango-1.0 gperf libatk1.0-dev libgsl0-dev libgtk2.0-dev libgtksourceview2.0-dev libharfbuzz-dev libharfbuzz-gobject0 libintl-perl libkpathsea6 libpango1.0-dev libptexenc1 librsvg2-bin libtext-diff-perl libtext-unidecode-perl libxcomposite-dev libxcursor-dev libxi-dev libxinerama-dev libxml-libxml-perl libxml-namespacesupport-perl libxml-sax-base-perl libxml-sax-perl libxml2-utils libxrandr-dev x11proto-composite-dev x11proto-randr-dev x11proto-xinerama-dev -y
 - wget "http://ftp.download-by.net/gnu/gnu/pspp/pspp-0.8.5.tar.gz" -O - | tar xvz
 - cd pspp*
 - ./configure
 - make -j4 >make_stdout.log 2>make_stderr.log
 - sudo make install
 - cd ..

 # Elasticsearch
 - wget --no-check-certificate https://hmbastiaan.nl/martijn/amcat/hitcount.jar
 - wget --no-check-certificate https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.3.tar.gz -O - | tar xvz
 - cd elasticsearch-1*
 - bin/plugin -install elasticsearch/elasticsearch-lang-python/2.4.1
 - bin/plugin -install elasticsearch/elasticsearch-analysis-icu/2.4.2
 - bin/plugin -install mobz/elasticsearch-head
 # I'm absolutely, thorougly annoyed by the syntax below.
 - "tee -a ./config/elasticsearch.yml <<< 'script.disable_dynamic: false'"
 - cd ..
 - ES_CLASSPATH=hitcount.jar elasticsearch-1*/bin/elasticsearch -Des.index.similarity.default.type=nl.vu.amcat.HitCountSimilarityProvider -d
 - pip install -r requirements.txt
 - pip install coverage coveralls
 - celery -A amcat.amcatcelery worker -l DEBUG -Q amcat &
 - npm install -g bower
 - bower install

script:
 - coverage run --source=. --omit=*/migrations/*,settings/* -m amcat.manage test

after_success:
 - coverage report -m
 - coveralls